### PR TITLE
correct incorrect descriptions of output

### PR DESCRIPTION
**Pull request by drelliche**
This closes https://github.com/arcus/education_modules/issues/225

### CODE REVIEW

**Review by franzenr — APPROVED** [review]
LGTM

**Comment by franzenr** [comment]
WAIT

**Comment by franzenr** [comment]
version number needs to be incremented ... one moment.

**Review by franzenr — CHANGES_REQUESTED** [review]
increment version number

**Comment by franzenr** [comment]
I suggested a minor version change, since it isn't as simple as just a typo, but rather some of the info was actually incorrect, but I don't thnk the module was changed enough to warrant a major. We don't cover this exact scenario in our [versioning guidelines](https://github.com/arcus/education_modules/blob/main/versioning_guidelines.md) so I'm curious what your thoughts are/if you're ok with the version number I chose @drelliche

**Comment by drelliche** [comment]
I'm good with this being a "minor version change." I had been thinking of it as a typo, but since it was actually incorrect information, I agree it should be at 1.2.0

**Review by franzenr — APPROVED** [review]

**Pull request merged**
